import { Passage } from "../types";

export const PASSAGES: Passage[] = [
  { id: "p1", difficulty: "easy", text: "The quick brown fox jumps over the lazy dog near the old wooden fence." },
  { id: "p2", difficulty: "easy", text: "She sells seashells by the seashore every single morning before breakfast." },
  { id: "p3", difficulty: "easy", text: "A gentle breeze moved through the trees as the sun began to set slowly." },
  { id: "p4", difficulty: "easy", text: "My favorite hobby is reading books about faraway places and old cities." },
  { id: "p5", difficulty: "easy", text: "The cat sat quietly on the windowsill watching birds fly across the sky." },
  { id: "p6", difficulty: "easy", text: "We walked along the beach collecting shells and watching the waves roll in." },
  { id: "p7", difficulty: "medium", text: "Typing quickly and accurately requires practice, patience, and a good understanding of keyboard layout." },
  { id: "p8", difficulty: "medium", text: "The committee reviewed the proposal carefully before deciding to approve the new budget for next year." },
  { id: "p9", difficulty: "medium", text: "Modern software development relies heavily on collaboration, version control, and continuous integration pipelines." },
  { id: "p10", difficulty: "medium", text: "Scientists discovered a new species of deep-sea fish that can survive extreme pressure and near-freezing temperatures." },
  { id: "p11", difficulty: "medium", text: "Effective communication in the workplace often depends on clarity, active listening, and mutual respect between colleagues." },
  { id: "p12", difficulty: "medium", text: "The museum's newest exhibit features artifacts from ancient civilizations that thrived thousands of years before recorded history." },
  { id: "p13", difficulty: "medium", text: "Renewable energy sources like solar and wind power are becoming increasingly cost-effective compared to fossil fuels." },
  { id: "p14", difficulty: "medium", text: "Learning a new language as an adult can be challenging, but consistent daily practice makes a significant difference." },
  { id: "p15", difficulty: "hard", text: "Quantum computing leverages the principles of superposition and entanglement to perform calculations that are infeasible for classical computers." },
  { id: "p16", difficulty: "hard", text: "The labyrinthine bureaucracy of the organization made even the simplest administrative tasks unnecessarily time-consuming and frustrating." },
  { id: "p17", difficulty: "hard", text: "Neuroscientists continue to unravel the extraordinarily complex mechanisms by which synaptic plasticity underlies learning and memory formation." },
  { id: "p18", difficulty: "hard", text: "The philosopher argued that epistemological skepticism, when taken to its logical extreme, ultimately undermines its own foundational premises." },
  { id: "p19", difficulty: "hard", text: "Cryptographic protocols must be rigorously vetted against adversarial attacks before being deployed in security-critical infrastructure systems." },
  { id: "p20", difficulty: "hard", text: "The juxtaposition of impressionist and cubist techniques in her later work exemplifies a fascinating evolution in artistic philosophy." },
  { id: "p21", difficulty: "hard", text: "Macroeconomic policy decisions, particularly those involving interest rates, ripple through financial markets with often unpredictable consequences." },
  { id: "p22", difficulty: "medium", text: "Volunteers spent the weekend planting trees along the riverbank to help restore the area's natural ecosystem." },
];
